#
# User configuration sourced by interactive shells
#

# Define zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

export PATH="/home/soorya/.local/bin:/home/soorya/.cabal/bin:/home/soorya/bin:$PATH:/opt/cuda/bin:/home/soorya/.emacs.d/bin:/opt/miniconda3/condabin/"

[ -f ~/.bash_aliases  ] && . ~/.bash_aliases
[ -f ~/.bash_functions  ] && . ~/.bash_functions
[ -f ~/dotfiles/shell/fzf.zsh ] && . ~/dotfiles/shell/fzf.zsh
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh

fortune | pokemonsay

autoload -Uz compinit
compinit

setopt histignorespace
setopt clobber
export EDITOR="emacsclient -tc"
export TERM="xterm-256color"

