# autoload -U promptinit; promptinit
# prompt pure

# Path to your oh-my-zsh installation.
export ZSH=/home/soorya/.oh-my-zsh
export STARDICT_DATA_DIR=~
HISTFILE=~/.bash_history
HISTSIZE=99999999
SAVEHIST=$HISTSIZE
#Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="philips"
# ZSH_THEME="af-magic"
#philips
#bira
# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="dd/mm/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(web_search z git common-aliases colored-man-pages mercurial zsh-syntax-highlighting)
# User configuration

export PATH="/home/soorya/.local/bin:/home/soorya/bin:/home/soorya/bin/git-scripts:/home/soorya/krita/inst/bin:/home/soorya/bin:/home/soorya/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/soorya/scripts:/home/soorya/.local/bin:/home/soorya/.cargo/bin:/home/soorya/bin/cross/bin:/home/soorya/clones/LLVM/orig/llvm_build/bin"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export EDITOR='vim'
# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

#Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
if [ -f ~/.bash_aliases  ]; then
   . ~/.bash_aliases
fi
if [ -f ~/.bash_functions  ]; then
   . ~/.bash_functions
fi

export PATH="/home/soorya/.cabal/bin:/usr/bin/core_perl:/home/soorya/.gem/ruby/2.4.0/bin:$PATH"

function collapse_pwd {
    echo $(pwd | sed -e "s,^$HOME,~,")
}

function prompt_char {
    git branch >/dev/null 2>/dev/null && echo '±' && return
    hg root >/dev/null 2>/dev/null && echo '☿' && return
    echo '$'
}

function battery_charge {
    echo `$BAT_CHARGE` 2>/dev/null
}

function virtualenv_info {
    [ $VIRTUAL_ENV ] && echo '('`basename $VIRTUAL_ENV`') '
}

#function hg_prompt_info {
#    hg --angle-brackets "\
#< on %{$fg[magenta]%}<branch>%{$reset_color%}>\
#< at %{$fg[yellow]%}<tags|%{$reset_color%}, %{$fg[yellow]%}>%{$reset_color%}>
#%{$fg[green]%}<status|modified|unknown><update>%{$reset_color%}<
#patches: <patches|join( → )|pre_applied(%{$fg[yellow]%})|post_applied(%{$reset_color%})|pre_unapplied(%{$fg_bold[black]%})|post_unapplied(%{$reset_color%})>>" 2>/dev/null
#}

# PROMPT='%{$fg[blue]%}%n%{$reset_color%} at %{$fg[green]%}%m%{$reset_color%} in %{$fg_bold[green]%}$(collapse_pwd)%{$reset_color%}$(hg_prompt_info)$(git_prompt_info)
# $(virtualenv_info)$(prompt_char) '

RPROMPT='$(battery_charge)'

# ZSH_THEME_GIT_PROMPT_PREFIX=" on %{$fg[magenta]%}"
# ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
# ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[green]%}!"
# ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[green]%}?"
# ZSH_THEME_GIT_PROMPT_CLEAN=""
# ZSH_THEME_HG_PROMPT_PREFIX=" %{$fg_bold[magenta]%}hg:(%{$fg[red]%}"
# ZSH_THEME_HG_PROMPT_SUFFIX="%{$reset_color%}"
# ZSH_THEME_HG_PROMPT_DIRTY="%{$fg[magenta]%}) %{$fg[yellow]%}✗%{$reset_color%}"
# ZSH_THEME_HG_PROMPT_CLEAN="%{$fg[magenta]%})"
#xterm transparency
[ -n "$XTERM_VERSION"  ] && transset-df --id "$WINDOWID" 0.91 >/dev/null

#so as not to be disturbed by Ctrl-S ctrl-Q in terminals:
stty -ixon

# log directory so that new terminal opens up there
#function cd {
#    builtin cd $@
#    pwd > ~/.last_dir
#}
# restore last saved path
#if [ -f ~/.last_dir  ]
#   then cd "`cat ~/.last_dir`"
#fi
if [[ $TERM == xterm-termite  ]]; then
    . /etc/profile.d/vte.sh
     __vte_osc7
fi

if [ -n "$INSIDE_EMACS"  ]; then
    export EDITOR=emacsclient
    unset zle_bracketed_paste  # This line
fi

# (wal -r &)
export PATH="/home/soorya/clones/ctf-tools/bin:/usr/bin/vendor_perl:$PATH"

export PATH="/home/soorya/Downloads/wine-2.2:/home/soorya/.gem/ruby/2.5.0/bin:/home/soorya/Documents/clones/LLVM/orig/llvm_build/bin:/usr/share/perl6/vendor/bin:$PATH"

export LD_LIBRARY_PATH='$LD_LIBRARY_PATH:/usr/local/lib'

# OPAM configuration
. /home/soorya/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
eval $(thefuck --alias)
# added by Anaconda3 4.4.0 installer
export PATH="$PATH:/home/soorya/anaconda3/bin:"
export PATH="/home/soorya/Documents/Programmes/Intern/pkd/code/verse-coq/coq-8.6/system/bin:$PATH"
export PATH="/opt/cuda/bin:$PATH"

source ~/bin/tmuxinator.zsh
source ~/bin/zsh-completion-yay 2> /dev/null
source /etc/profile.d/autojump.zsh

