#
# User configuration sourced by interactive shells
#

# Define zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

export PATH="/home/soorya/.local/bin:/home/soorya/.cabal/bin:/home/soorya/bin:$PATH:/opt/cuda/bin"

[ -f ~/.bash_aliases  ] && . ~/.bash_aliases
[ -f ~/.bash_functions  ] && . ~/.bash_functions
[ -f ~/dotfiles/shell/fzf.zsh ] && . ~/dotfiles/shell/fzf.zsh
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh

fortune | pokemonsay

autoload -Uz compinit
compinit

setopt histignorespace
setopt clobber
# source ~/dotfiles/shell/powerlevel10k/powerlevel10k.zsh-theme


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /usr/share/autojump/autojump.zsh ] && source /usr/share/autojump/autojump.zsh

# Ottomatika Environment
#export OTTO_DIR=/home/soorya/.conan/data/aptivware/0.99/jenkins/PR-17-6463def/package/1cc155b4f1e22eaea47cf529d44dbfb8b6209b1e
export OTTO_DIR=/home/soorya/ottomatika_package
export OTTO_CONFIG_DIR=$OTTO_DIR/config
export APTIV_MAP_DIR=$OTTO_DIR/models
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${OTTO_DIR}/lib
export PATH=${OTTO_DIR}/bin:${OTTO_DIR}/scripts:${HOME}/go/bin:${PATH}:/home/soorya/.gem/ruby/2.5.0/bin
export ACTIVE_CONFIG_DIR=${OTTO_DIR}/active
export PATH=/usr/local/cuda-10.2/bin:$PATH
export DOTNET_CLI_TELEMETRY_OPTOUT=true
export EDITOR=vim

# [ -z "$TMUX"  ] && { tmux attach || exec tmux new-session && exit;}

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/soorya/.miniconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/soorya/.miniconda/etc/profile.d/conda.sh" ]; then
        . "/home/soorya/.miniconda/etc/profile.d/conda.sh"
    else
        export PATH="/home/soorya/.miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
conda activate prediction

setopt AUTO_PUSHD