#!/usr/bin/env bash
alias a='sudo service network-manager restart;sleep 4;timeout 2 limras'
alias apt-get='apt'
alias apt-history='subl /var/log/apt/history.log'
alias b='upower -d | grep time | head -n 1'
alias battery='upower -d|grep "time to empty"'
alias bc='bc -l'
alias bgd='bg;disown'
alias prettybig='toilet -f future '
#alias cabal='cabal-1.24'
alias chrome='google-chrome &'
alias clam='sudo freshclam; clamscan -r --bell -i'
alias cling='cling --nologo -l bits/stdc++.h -l stdlib.h -l stdio.h -l iostream'
alias count='ls | wc -l'
alias cppcheck='cppcheck --enable=all --inconclusive --std=posix --check-config '
alias cv='cd ~/Documents/Personal/Deedy-Resume/OpenFonts/'
alias dup='gnome-terminal &'
alias ec='emacsclient'
alias expose='~/Clones/Expose/expose.sh'
alias f='find . -name '
alias feh='feh -.'
alias g++="g++ --std=c++0x"
alias gb='git branch'
alias gdh='git diff HEAD~1 HEAD'
alias gdmMod='cd /usr/share/gnome-shell/theme/'
#alias ghci='ghci-color'
alias ghci-core="ghci -ddump-simpl -dsuppress-idinfo \
    -dsuppress-coercions -dsuppress-type-applications \
    -dsuppress-uniques -dsuppress-module-prefixes"
alias ghcver='cd /usr/local/stow && sudo stow'
alias gits='git status -s'
alias gitl='git log --pretty=oneline'
alias gpom='git pull origin master'
alias hsoc='cd ~/Documents/Programmes/HSOC/hackage-server'
alias i3-exit='i3-msg exit'
alias i3cheatsheet='egrep ^bind ~/.i3/config | cut -d '\'' '\'' -f 2- | sed '\''s/ /\t/'\'' | column -ts $'\''\t'\'' | pr -2 -w 145 -t | less'
alias i3conf='vim ~/.i3/config'
alias Install='sudo apt-fast -y install'
alias jcryptool='~/bin/jcryptool/JCrypTool &'
alias llogin='screen elinks 172.168.10.1;clear'
alias ls='ls --color=auto'
alias mirror_website='wget --mirror -p --html-extension --convert-links'
alias mountWindows='sudo mount -t ntfs-3g -o ro /dev/sda4 /media/Windows'
alias mwos='cd ~/Documents/Programmes/MWoS/'
alias n='nautilus . 2> /dev/null & disown'
alias ncmpcpp_='sudo pkill mpd;mpd;ncmpcpp'
alias netStop='sudo service network-manager stop;wicd-gtk &'
alias newalias='vim ~/.bash_aliases;. ~/.bash_aliases;'
alias newfunction='vim ~/.bash_functions;. ~/.bash_functions;'
alias p3='ipython3'
alias packages='sudo dpkg --get-selections > ~/.package_list;pip freeze > ~/.pip_packages'
alias pdf2html='pdf2htmlEX --process-outline 0 --zoom 1.4 '
alias pgcc='gcc `pkg-config --libs --cflags python2` -c'
alias phperror='sudo tail -f /var/log/apache2/error.log'
alias phpmyadminuser='sudo htpasswd -c /etc/apache2/.phpmyadmin.htpasswd username'
alias pips='sudo -H pip2 install --upgrade '
alias pip3s='sudo -H pip3 install --upgrade '
alias p='ipython'
alias ppt2pdf='libreoffice --headless --invisible --convert-to pdf'
alias pserve='python3 -m http.server'
alias publicIP='curl http://icanhazip.com'
alias q='2> /dev/null'
alias quotes='vim .quotes'
alias ranger='ranger --choosedir=$HOME/rangerdir; LASTDIR=`cat $HOME/rangerdir`; cd "$LASTDIR"'
alias redshift_='redshift -l 10.790483:78.704673 & disown'
alias reminders='vim ~/.reminders'
alias rm='rm -i'
alias s='sudo'
alias speaketh='toilet -f pagga '
#alias spotify='spotify %U --ap=194.132.196.162'
alias syllabus='open /home/soorya/Documents/NITT/SyllabusNITT.pdf'
alias todo='vim ~/TODO.org'
alias underscore='find -name "* *" -type f | rename "s/ /_/g"'
alias Update='sudo apt update'
alias Upgrade='Update && sudo apt upgrade && sudo apt autoremove'
alias tempDir='cd $(mktemp -d)'
alias vimp='vim ~/.vimperatorrc'
alias vimrc='vim ~/.vimrc'
alias volBoost='pactl -- set-sink-volume 0 150%'
alias wifidrop='echo "options rtl8723be fwlps=0" | sudo tee /etc/modprobe.d/rtl8723be.conf'
alias wifirestart='sudo rmmod rtl8723be && sudo modprobe rtl8723be'
alias xterm="xterm -fa 'Monospace' -fs 11"
alias ydlo='ydl --playlist-start'
alias ydlmo='ydlm --playlist-start'
alias ydl='youtube-dl --prefer-ffmpeg'
alias ydlm='ydl --extract-audio --audio-format mp3'
#alias youtube-rename='ls | sed 's/\(.*\)\(-.*\)/mv \"&\" \"\1.mp3\"/' | bash'
alias y='yes| '
#rename 's/\d+/sprintf("%04d",$&)/e' *.png

alias doc='cd ~/Documents/'
alias dl='cd ~/Downloads/'
alias music='cd ~/Music/'
alias pic='cd ~/Pictures/'
alias vid='cd ~/Videos/'
alias win='cd /media/soorya/Windows/Users/soory/'
alias clones='cd ~/clones/'
alias nitt='cd ~/Documents/NITT/Sem\ VI'
alias fam='cd ~/Documents/Family/'
alias codechar='cd ~/delta/code_character'
